### ISSUE TITLE
Want PQL fromdate and todate structure. 

### ISSUE THREAD

**Issue by sunbarve** [alonho/pql#22]
I want $gte,$lte for same field in PQL, so how can i do this.

mongo query:
{'updated_on': {'$gte': datetime.datetime(2012, 2, 4, 0, 0),'$lte': datetime.datetime(2012, 3, 4, 0, 0)}}

I want PQL string structure for this mongo query.

Thanking you.

**Comment by alonho** [comment]
I don't remember if this is supported: date(...) <= updated_on <= date(...)
But this definitely works: updated_on > date(...) and updated_on < date(...)
It generates an $and but I don't think that's an issue.

**Comment by sunbarve** [comment]
Solved this issue,so close it.
