### ISSUE TITLE
Bug on $near query

### ISSUE THREAD

**Issue by mesarvagya** [alonho/pql#23]
There is an error while creating query for GeoQueries, especially near. Your example location == near([1, 2], 10) generates _{'location': SON([('$near', [1, 2]), ('$maxDistance', 10)])}_, where SON([( is some random characters (possibly missing { and } ). It is replicated for _location == near(Point(1, 2), 10)_ and _location == nearSphere(Point(1, 2))_ . Thanks.

**Comment by alonho** [comment]
It's not a bug. SON([('a', 1), ('b', 2)]) is actually an ordered dictionary implemented by pymongo (python's dictionary is unordered).
